#!/usr/bin/env python3

import subprocess
import sys


def run_diffduck_pre_push() -> int:
    process = subprocess.Popen(["./diffduck pre-push"], shell=True)
    process.wait()
    return process.returncode

if __name__ == "__main__":
    print(sys.argv)
    for line in sys.stdin:
        print(line)

    return_code = run_diffduck_pre_push()
    sys.exit(return_code)
