#!/usr/bin/env python3

import sys

print("Hello, world!")

print(sys.argv)
for line in sys.stdin:
    print(line)

sys.exit(0)

### Create new branch on remote
# ['.githooks/pre-push', 'origin', 'https://github.com/DiffDuck/diffduck']
# refs/heads/chenbobby--feature-branch b15e552896e51d942da3d911531e1cd9810a6d3b refs/heads/chenbobby--feature-branch 0000000000000000000000000000000000000000
#
# <branch name> <new sha> <branch name> <zero sha>

### Update existing branch on remote
# ['.githooks/pre-push', 'origin', 'https://github.com/DiffDuck/diffduck']
# refs/heads/chenbobby--feature-branch a952528ce86e95ec686ce9e41b9fd7743c6fa9f5 refs/heads/chenbobby--feature-branch 00c71b887c0d97a7c9c1785d9f592faa21da7839
#
# <branch name> <new sha> <branch name> <old sha>

### Delete a branch on remote
# git push origin --delete chenbobby--feature-branch
#
# ['.githooks/pre-push', 'origin', 'https://github.com/DiffDuck/diffduck']
# (delete) 0000000000000000000000000000000000000000 refs/heads/chenbobby--feature-branch 0294e763a00c948bfd7c4ba783108eff7751e315
#
# (delete) <zero sha> <branch name> <old sha>

### Creating a tag on remote
# git push --tags
#
# ['.githooks/pre-push', 'origin', 'https://github.com/DiffDuck/diffduck']
# refs/tags/my-tag fd21775729c4476a1a07693af7b21b7eb5ddaa89 refs/tags/my-tag 0000000000000000000000000000000000000000
#
# <tag name> <new sha> <tag name> <zero sha>
