#!/usr/bin/env python3


import sys


def amend_commit(path, type, sha):
    print(path)
    print(type)
    print(sha)


def new_commit(path):
    pass


if __name__ == "__main__":
    COMMIT_MESSAGE_TMP_FILE_PATH = sys.argv[1]

    if len(sys.argv) == 2:
        new_commit(COMMIT_MESSAGE_TMP_FILE_PATH)

    if len(sys.argv) == 4:
        COMMIT_TYPE = sys.argv[2]
        COMMIT_SHA = sys.argv[3]
        amend_commit(COMMIT_MESSAGE_TMP_FILE_PATH, )
